import { describe, it, expect, beforeAll, afterAll, vi } from "vitest";

vi.mock("../services/ai", () => {
  const fakeExtractionResult = {
    epics: [
      {
        id: "smoke-epic-0",
        title: "Smoke Epic",
        description: "Generated by smoke test mock",
        tickets: [
          {
            id: "SMOKE-T1",
            epicId: "smoke-epic-0",
            title: "Smoke Ticket",
            type: "feature",
            priority: "P1",
            storyPoints: 2,
            status: "backlog",
            dependencies: [],
            description: "Mock ticket",
            acceptanceCriteria: [
              "Given a mock When called Then it returns",
              "Given data When validated Then it passes",
              "Given a system When smoke tested Then it works",
            ],
            aiDevPrompt: "Smoke test implementation instructions.",
          },
        ],
      },
    ],
    validationReport: {
      targetStack: null,
      stackProvided: false,
      matchScore: 0,
      compatibilityGaps: [],
      recommendations: [],
    },
  };

  const fakeTicket = {
    id: "SMOKE-T2",
    title: "Smoke Extracted Ticket",
    type: "feature",
    priority: "P1",
    storyPoints: 2,
    dependencies: [],
    description: "Extracted by smoke test",
    acceptanceCriteria: [
      "Given x When y Then z",
      "Given a When b Then c",
      "Given p When q Then r",
    ],
    aiDevPrompt: "Smoke extraction instructions.",
  };

  const fakeClient = {
    chat: {
      completions: {
        create: vi.fn().mockResolvedValue({
          choices: [
            {
              message: {
                content: JSON.stringify(fakeTicket),
              },
            },
          ],
        }),
      },
    },
  };

  return {
    createDeepSeekClient: vi.fn().mockReturnValue(fakeClient),
    extractBacklog: vi.fn().mockResolvedValue(fakeExtractionResult),
  };
});

import { buildApp } from "../server";
import { getPool, createPool, closePool } from "../db/pool";
import type { FastifyInstance } from "fastify";

let server: FastifyInstance;

describe("E2E smoke test", () => {
  beforeAll(async () => {
    createPool();
    server = await buildApp();
    await server.ready();

    const pool = getPool();
    await pool.query(
      `INSERT INTO epics (id, title, description)
       VALUES ($1, $2, $3)
       ON CONFLICT (id) DO NOTHING`,
      ["e2e-epic-0", "E2E Test Epic", "Epic for smoke testing"],
    );
  }, 15000);

  afterAll(async () => {
    if (server) await server.close();
    await closePool();
  });

  it("health check returns ok", async () => {
    const res = await server.inject({
      method: "GET",
      url: "/trpc/health",
    });

    expect(res.statusCode).toBe(200);
    const body = JSON.parse(res.body) as {
      result: { data: { status: string; timestamp: number } };
    };

    expect(body.result.data.status).toBe("ok");
    expect(typeof body.result.data.timestamp).toBe("number");
  });

  it("Swagger docs page is served at /docs", async () => {
    const res = await server.inject({
      method: "GET",
      url: "/docs",
    });

    expect(res.statusCode).toBe(200);
    expect(res.body).toContain("swagger");
  });

  it("Swagger JSON spec is served at /docs/json", async () => {
    const res = await server.inject({
      method: "GET",
      url: "/docs/json",
    });

    expect(res.statusCode).toBe(200);
    const spec = JSON.parse(res.body) as Record<string, unknown>;

    expect(spec["info"]).toBeDefined();
    expect(spec["paths"]).toBeDefined();
  });

  it("uploadBrd returns an uploadId", async () => {
    const res = await server.inject({
      method: "POST",
      url: "/trpc/brd.uploadBrd",
      payload: {
        fileBase64: Buffer.from("Sample BRD for e2e test").toString(
          "base64",
        ),
        fileName: "e2e-test.txt",
      },
      headers: { "content-type": "application/json" },
    });

    expect(res.statusCode).toBe(200);
    const body = JSON.parse(res.body) as {
      result: { data: { uploadId: string } };
    };

    expect(body.result.data.uploadId).toBeDefined();
  });

  it("getUploadStatus returns the upload record", async () => {
    const uploadRes = await server.inject({
      method: "POST",
      url: "/trpc/brd.uploadBrd",
      payload: {
        fileBase64: Buffer.from("Another test BRD").toString("base64"),
        fileName: "status-test.txt",
      },
      headers: { "content-type": "application/json" },
    });

    const uploadBody = JSON.parse(uploadRes.body) as {
      result: { data: { uploadId: string } };
    };
    const uploadId = uploadBody.result.data.uploadId;

    const res = await server.inject({
      method: "GET",
      url: `/trpc/brd.getUploadStatus?input=${encodeURIComponent(JSON.stringify({ uploadId }))}`,
    });

    expect(res.statusCode).toBe(200);
    const body = JSON.parse(res.body) as {
      result: { data: { status: string } };
    };

    expect(
      ["pending", "processing", "completed", "failed"],
    ).toContain(body.result.data.status);
  });

  it("getBacklog returns an array", async () => {
    const res = await server.inject({
      method: "GET",
      url: "/trpc/backlog.getBacklog",
    });

    expect(res.statusCode).toBe(200);
    const body = JSON.parse(res.body) as {
      result: { data: unknown };
    };

    expect(Array.isArray(body.result.data)).toBe(true);
  });

  it("createTicket persists and returns the ticket", async () => {
    const res = await server.inject({
      method: "POST",
      url: "/trpc/backlog.createTicket",
      payload: {
        id: "E2E-T1",
        epicId: "e2e-epic-0",
        title: "E2E Smoke Ticket",
        type: "feature",
        priority: "P1",
        storyPoints: 2,
        status: "backlog",
        dependencies: [],
        description: "Smoke test ticket",
        acceptanceCriteria: ["Given x When y Then z", "Given a When b Then c", "Given p When q Then r"],
        aiDevPrompt: "E2E test",
      },
      headers: { "content-type": "application/json" },
    });

    expect(res.statusCode).toBe(200);
    const body = JSON.parse(res.body) as {
      result: { data: { id: string; title: string } };
    };

    expect(body.result.data.id).toBe("E2E-T1");
    expect(body.result.data.title).toBe("E2E Smoke Ticket");
  });

  it("updateTicketStatus changes status", async () => {
    const res = await server.inject({
      method: "POST",
      url: "/trpc/backlog.updateTicketStatus",
      payload: {
        ticketId: "E2E-T1",
        status: "in_progress",
      },
      headers: { "content-type": "application/json" },
    });

    expect(res.statusCode).toBe(200);
    const body = JSON.parse(res.body) as {
      result: { data: { id: string; status: string } };
    };

    expect(body.result.data.id).toBe("E2E-T1");
    expect(body.result.data.status).toBe("in_progress");
  });

  it("extractTicketFromPrompt returns extracted ticket", async () => {
    const res = await server.inject({
      method: "POST",
      url: "/trpc/backlog.extractTicketFromPrompt",
      payload: {
        prompt: "Add user authentication with JWT tokens",
        epicId: "e2e-epic-0",
      },
      headers: { "content-type": "application/json" },
    });

    expect(res.statusCode).toBe(200);
    const body = JSON.parse(res.body) as {
      result: { data: { id: string; title: string } };
    };

    expect(body.result.data.id).toBe("SMOKE-T2");
    expect(body.result.data.title).toBe("Smoke Extracted Ticket");
  });
});
